# services:
#   mysql:
#     image: 'mysql:latest'
#     environment:
#       - 'MYSQL_DATABASE=mydatabase'
#       - 'MYSQL_PASSWORD=secret'
#       - 'MYSQL_ROOT_PASSWORD=verysecret'
#       - 'MYSQL_USER=myuser'
#     ports:
#       - '3306'


version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    container_name: fitpet-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: fitpet_root_2024
      MYSQL_DATABASE: fitpet_db
      MYSQL_USER: fitpet_user
      MYSQL_PASSWORD: fitpet_pass_2024
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fitpet-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
 
# deben estar activas para que los servicios funcionen.
volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
    
networks:
  fitpet-network:
    driver: bridge