version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    container_name: fitpet-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: fitpet_root_2024
      MYSQL_DATABASE: fitpet_db
      MYSQL_USER: fitpet_user
      MYSQL_PASSWORD: fitpet_pass_2024
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fitpet-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: .
    container_name: fitpet-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fitpet_db
      SPRING_DATASOURCE_USERNAME: fitpet_user
      SPRING_DATASOURCE_PASSWORD: fitpet_pass_2024
    networks:
      - fitpet-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
    
networks:
  fitpet-network:
    driver: bridge